services:
  imersao-alura-devops-refactored-octo-chainsaw:
    container_name: imersao-alura-devops-refactored-octo-chainsaw
    restart: unless-stopped
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - imersao-alura-devops-refactored-octo-chainsaw-data:/app

volumes:
  imersao-alura-devops-refactored-octo-chainsaw-data: